version: 2
# registries:
#   npm-github:
#     type: npm-registry
#     url: https://npm.pkg.github.com
#     token: ${{secrets.NPM_AUTH_TOKEN}}
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/'
    registries:
      - npm-github
    schedule:
      interval: 'weekly'
    groups:
      # This is the name of your group, it will be used in PR titles and branch names
      eslint-dependencies:
        patterns:
          - ^eslint
