name: Check

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JS
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
      - run: yarn install --frozen-lockfile # optional, --immutable
      - run: yarn test
      - run: yarn lint
